---
title: "Refcard pandoc citeproc"
output: 
  github_document:
    toc: true
link-citations: true
bibliography: refs.bib
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)

knitr::opts_chunk$set(
  echo = TRUE
  )


# Markdown pseudo-engine
knit_engines$set(
  markdown = function(options) {
    opt <- options
    opt$results <- "asis"
    engine_output(
      options = opt, 
      code = options$code,
      out = paste(options$code, collapse="\n")
      )
  }
)
```

# Worthwhile metadata options

- `link-citations: [true|false]` -- convert year to a hyperlink in reference list


# Examples

```{markdown}
Blah blah [@wf;@coleman].
```


```{markdown}
Blah blah [see @wf, pp. 33-35; also @coleman, chap. 1].
```




# Locator terms

```{markdown}
see [@wf, book 1, chap. 1, pp. 33-35]
```

```{markdown}
see @wf [book 1]
```


```{markdown}
see @wf [chapter 1]
```

```{markdown}
see @wf [column 1]
```

```{markdown}
see @wf [figure 1]
```

```{markdown}
see @wf [folio 1]
```

```{markdown}
see @wf [number 1]
```

```{markdown}
see @wf [line 1]
```

```{markdown}
see @wf [note 1]
```

```{markdown}
see @wf [opus 1]
```

```{markdown}
see @wf [paragraph 1]
```

```{markdown}
see @wf [part 1]
```

```{markdown}
see @wf [section 1]
```

```{markdown}
see @wf [sub verbo 1]
```

```{markdown}
see @wf [verse 1]
```

```{markdown}
see @wf [volume 1]
```


## Protect locators with curly braces

```{markdown}
[@wf{ii, A, D-Z}, with suffix]
```

```{markdown}
[@wf, {chapter iv, vi-xi} with suffix here]
```


```{markdown}
@wf [chapter 33] or 
Wasserman says blah again [-@wf]
```

# Appendix A: BibTeX file {-}

```{r}
cat(readLines("refs.bib"), sep="\n")
```


# Appendix B: Software

```{r}
rmarkdown::pandoc_version()
system2("pandoc-citeproc", "--version", stdout=TRUE)
```



# Forced references 

::: {#refs}
:::


# References {-}